name: test

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: npm ci
      - name: build:html
        run: npm run build:html
      - name: build:css
        run: npm run build:css
      - name: test
        run: npm run test
